### Tensors are a fundamental data structure in PyTorch, similar to NumPy arrays, but with additional capabilities, particularly for deep learning applications. They can be processed on CPUs and GPUs, making them efficient for numerical computations.

In [1]:
import torch
print(torch.__version__)

2.5.1+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


In [3]:
# using empty
a=torch.empty(2,3)
print(a)

tensor([[-3.3899e-21,  2.1202e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [11]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

## Autograd Practice

In [49]:
x=torch.tensor(4.0,requires_grad=True)

In [59]:
y=x**2

In [60]:
y

tensor(16., grad_fn=<PowBackward0>)

In [61]:
y.backward()

In [62]:
x.grad

tensor(16.)

In [63]:
# clearing previous gradient
x.grad.zero_()

tensor(0.)

In [40]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [41]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [42]:
z = w*x + b

In [43]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [44]:
def Binay_loss_cross_entropy(prediction,target):
    epsilon=1e-8
    prediction=torch.clamp(prediction,epsilon,1-epsilon)
    return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [45]:
loss=Binay_loss_cross_entropy(y_pred,y)

In [46]:
loss.backward()

In [47]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)
